name: testing
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  salomon_bottom_bar: ^3.3.2
  lottie: ^3.3.2
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.5.0
  modal_bottom_sheet: ^3.0.0
  google_maps_flutter: ^2.13.1
  flutter_dotenv: ^6.0.0
  logger: ^2.6.2  
  uuid: ^4.5.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tutorial_icons/
    - assets/weather_icons/
    - .env 

